export const metadata = {
  title: 'Teodor Jakovljevic',
  description: 'Generated by Next.js',
  icons:{
    icon:"image/favicon.png"
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
